version: "3"

services:
  ngnix:
    build:
      context: .
      dockerfile: nginx.dockerfile
    ports:
      - "9000:9000"
      - "9090:9090"
    links:
      - app
      - vouch
  app:
    build:
      context: .
      dockerfile: app.dockerfile
  vouch:
    build:
      context: .
      dockerfile: vouch.dockerfile
